apiVersion: v1
kind: ConfigMap
metadata: 
  name: backend
  namespace: expense
data: 
  DB_HOST: mysql
 
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  namespace: expense
  labels: 
    project: expense
    app: backend
    tier: backend
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: expense
      app: backend
      tier: backend
  template:
    metadata: 
      labels: 
        project: expense
        app: backend
        tier: backend
    spec:
      containers:
      - name: backend
        image: lakshman143/backend:1.0.0
        envFrom:
        - configMapRef:
            name: backend
---
apiVersion: v1 
kind: Service
metadata: 
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    app: backend
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

